find_path(HELLO_INCLUDE_DIR hello.h /tmp/usr/include/hello)
find_library(HELLO_LIBRARY NAMES hello_d PATH /tmp/usr/lib)
if (HELLO_INCLUDE_DIR AND HELLO_LIBRARY)
    set(HELLO_FOUND true)
endif (HELLO_INCLUDE_DIR AND HELLO_LIBRARY)

if (HELLO_FOUND)
    if (NOT HELLO_FOUND_QUIETLY)
        message(STATUS "Found hello: ${HELLO_INCLUDE_DIR} ${HELLO_LIBRARY}")
    endif (NOT HELLO_FOUND_QUIETLY)
else(HELLO_FOUND)
    if (HELLO_FOUND_REQUIRED)
        message(FATAL_ERROR "couldn't find hello library")
    endif (HELLO_FOUND_REQUIRED)
endif (HELLO_FOUND)